config/routes.rb
Rails.application.routes.draw do
  root controller: :articles, action: :index
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title, :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(params.require(:article).permit(:title, :content))
    if article.persisted?
      binding.pry

      redirect_to @article, notice: "Article was successfully created."
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %><br />
    </li>
  <% end %>
  <%= link_to "New Article", new_article_path %>
</ul>

app/views/articles/new.html.erb
<h1>New article</h1>
<%= form_with scope: :article, local: true do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.label :content %>
    <%= form.text_area :content %>
    <%= form.submit "Create Article" %>
<% end %>

app/views/articles/show.html.erb
<p><%= @article.title %></p>
<p><%= @article.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>